begin;

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'words'
			and column_name = 'id'
			and is_identity = 'NO'
	) then
		alter table public.words
			alter column id add generated by default as identity;
	end if;
end $$;

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'tags'
			and column_name = 'id'
			and is_identity = 'NO'
	) then
		alter table public.tags
			alter column id add generated by default as identity;
	end if;
end $$;

create or replace function public.touch_word_updated_at()
returns trigger
language plpgsql
as $$
declare
	target_word_id integer;
begin
	target_word_id := coalesce(new.word_id, old.word_id);

	if target_word_id is not null then
		update public.words
		set updated_at = now()
		where id = target_word_id;
	end if;

	return coalesce(new, old);
end;
$$;

create or replace function public.set_word_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

drop trigger if exists words_set_updated_at on public.words;
create trigger words_set_updated_at
before update on public.words
for each row
execute function public.set_word_updated_at();

drop trigger if exists word_translations_touch_word_updated_at on public.word_translations;
create trigger word_translations_touch_word_updated_at
after insert or update or delete on public.word_translations
for each row
execute function public.touch_word_updated_at();

drop trigger if exists word_tags_touch_word_updated_at on public.word_tags;
create trigger word_tags_touch_word_updated_at
after insert or delete on public.word_tags
for each row
execute function public.touch_word_updated_at();

create or replace function public.validate_word_save_payload(
	p_translations jsonb,
	p_tag_ids integer[]
)
returns void
language plpgsql
as $$
declare
	normalized_tag_ids integer[];
	distinct_tag_count integer;
	existing_tag_count integer;
begin
	if coalesce(btrim(coalesce(p_translations->'zh-TW'->>'text', '')), '') = ''
		and coalesce(btrim(coalesce(p_translations->'id'->>'text', '')), '') = ''
		and coalesce(btrim(coalesce(p_translations->'en'->>'text', '')), '') = '' then
		raise exception 'At least one translation is required.';
	end if;

	normalized_tag_ids := coalesce(p_tag_ids, '{}'::integer[]);

	if exists (
		select 1
		from unnest(normalized_tag_ids) as tag_id
		where tag_id is null or tag_id <= 0
	) then
		raise exception 'Tag ids must be positive integers.';
	end if;

	select count(distinct tag_id), count(*)
	into distinct_tag_count, existing_tag_count
	from unnest(normalized_tag_ids) as tag_id;

	if distinct_tag_count <> existing_tag_count then
		raise exception 'Duplicate tag ids are not allowed.';
	end if;

	select count(*)
	into existing_tag_count
	from public.tags
	where id = any(normalized_tag_ids);

	if existing_tag_count <> cardinality(normalized_tag_ids) then
		raise exception 'One or more tags do not exist.';
	end if;
end;
$$;

create or replace function public.replace_word_relations(
	p_word_id integer,
	p_translations jsonb,
	p_tag_ids integer[]
)
returns void
language plpgsql
as $$
begin
	perform public.validate_word_save_payload(p_translations, p_tag_ids);

	insert into public.word_translations (word_id, language_code, text, pronunciation, audio_filename)
	values
		(
			p_word_id,
			'zh-TW',
			coalesce(btrim(coalesce(p_translations->'zh-TW'->>'text', '')), ''),
			coalesce(btrim(coalesce(p_translations->'zh-TW'->>'pronunciation', '')), ''),
			coalesce(btrim(coalesce(p_translations->'zh-TW'->>'audio_filename', '')), '')
		),
		(
			p_word_id,
			'id',
			coalesce(btrim(coalesce(p_translations->'id'->>'text', '')), ''),
			coalesce(btrim(coalesce(p_translations->'id'->>'pronunciation', '')), ''),
			coalesce(btrim(coalesce(p_translations->'id'->>'audio_filename', '')), '')
		),
		(
			p_word_id,
			'en',
			coalesce(btrim(coalesce(p_translations->'en'->>'text', '')), ''),
			coalesce(btrim(coalesce(p_translations->'en'->>'pronunciation', '')), ''),
			coalesce(btrim(coalesce(p_translations->'en'->>'audio_filename', '')), '')
		)
	on conflict (word_id, language_code) do update
	set
		text = excluded.text,
		pronunciation = excluded.pronunciation,
		audio_filename = excluded.audio_filename;

	delete from public.word_tags
	where word_id = p_word_id;

	insert into public.word_tags (word_id, tag_id)
	select p_word_id, tag_id
	from unnest(coalesce(p_tag_ids, '{}'::integer[])) as tag_id;
end;
$$;

create or replace function public.admin_create_word(
	p_image_url text default '',
	p_translations jsonb default '{}'::jsonb,
	p_tag_ids integer[] default '{}'::integer[]
)
returns public.words
language plpgsql
as $$
declare
	saved_word public.words;
begin
	insert into public.words (image_url)
	values (coalesce(btrim(coalesce(p_image_url, '')), ''))
	returning * into saved_word;

	perform public.replace_word_relations(saved_word.id, p_translations, p_tag_ids);

	select *
	into saved_word
	from public.words
	where id = saved_word.id;

	return saved_word;
end;
$$;

create or replace function public.admin_update_word(
	p_word_id integer,
	p_image_url text default '',
	p_translations jsonb default '{}'::jsonb,
	p_tag_ids integer[] default '{}'::integer[]
)
returns public.words
language plpgsql
as $$
declare
	saved_word public.words;
begin
	update public.words
	set image_url = coalesce(btrim(coalesce(p_image_url, '')), '')
	where id = p_word_id
	returning * into saved_word;

	if not found then
		return null;
	end if;

	perform public.replace_word_relations(saved_word.id, p_translations, p_tag_ids);

	select *
	into saved_word
	from public.words
	where id = saved_word.id;

	return saved_word;
end;
$$;

create or replace function public.validate_tag_save_payload(
	p_translations jsonb
)
returns void
language plpgsql
as $$
begin
	if coalesce(btrim(coalesce(p_translations->'zh-TW'->>'name', '')), '') = ''
		and coalesce(btrim(coalesce(p_translations->'id'->>'name', '')), '') = ''
		and coalesce(btrim(coalesce(p_translations->'en'->>'name', '')), '') = '' then
		raise exception 'At least one tag translation is required.';
	end if;
end;
$$;

create or replace function public.replace_tag_relations(
	p_tag_id integer,
	p_icon text,
	p_translations jsonb
)
returns void
language plpgsql
as $$
begin
	perform public.validate_tag_save_payload(p_translations);

	update public.tags
	set icon = coalesce(btrim(coalesce(p_icon, '')), 'sell')
	where id = p_tag_id;

	insert into public.tag_translations (tag_id, language_code, name)
	values
		(
			p_tag_id,
			'zh-TW',
			coalesce(btrim(coalesce(p_translations->'zh-TW'->>'name', '')), '')
		),
		(
			p_tag_id,
			'id',
			coalesce(btrim(coalesce(p_translations->'id'->>'name', '')), '')
		),
		(
			p_tag_id,
			'en',
			coalesce(btrim(coalesce(p_translations->'en'->>'name', '')), '')
		)
	on conflict (tag_id, language_code) do update
	set name = excluded.name;
end;
$$;

create or replace function public.admin_create_tag(
	p_icon text default 'sell',
	p_translations jsonb default '{}'::jsonb
)
returns public.tags
language plpgsql
as $$
declare
	saved_tag public.tags;
begin
	insert into public.tags (icon)
	values (coalesce(nullif(btrim(coalesce(p_icon, '')), ''), 'sell'))
	returning * into saved_tag;

	perform public.replace_tag_relations(saved_tag.id, saved_tag.icon, p_translations);

	select * into saved_tag from public.tags where id = saved_tag.id;
	return saved_tag;
end;
$$;

create or replace function public.admin_update_tag(
	p_tag_id integer,
	p_icon text default 'sell',
	p_translations jsonb default '{}'::jsonb
)
returns public.tags
language plpgsql
as $$
declare
	saved_tag public.tags;
begin
	update public.tags
	set icon = coalesce(nullif(btrim(coalesce(p_icon, '')), ''), 'sell')
	where id = p_tag_id
	returning * into saved_tag;

	if not found then
		return null;
	end if;

	perform public.replace_tag_relations(saved_tag.id, saved_tag.icon, p_translations);

	select * into saved_tag from public.tags where id = saved_tag.id;
	return saved_tag;
end;
$$;

create or replace function public.admin_delete_tag(
	p_tag_id integer
)
returns boolean
language plpgsql
as $$
declare
	tag_usage_count integer;
begin
	if not exists (select 1 from public.tags where id = p_tag_id) then
		return false;
	end if;

	select count(*)
	into tag_usage_count
	from public.word_tags
	where tag_id = p_tag_id;

	if tag_usage_count > 0 then
		raise exception 'Tag is still in use.';
	end if;

	delete from public.tags where id = p_tag_id;
	return true;
end;
$$;

commit;
